package entity;
// Generated 08/07/2017 8:14:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * DeliveryCost generated by hbm2java
 */
public class DeliveryCost  implements java.io.Serializable {


     private Integer deliveryId;
     private String zoneName;
     private double deliveryCost;
     private Set orders = new HashSet(0);

    public DeliveryCost() {
    }

	
    public DeliveryCost(String zoneName, double deliveryCost) {
        this.zoneName = zoneName;
        this.deliveryCost = deliveryCost;
    }
    public DeliveryCost(String zoneName, double deliveryCost, Set orders) {
       this.zoneName = zoneName;
       this.deliveryCost = deliveryCost;
       this.orders = orders;
    }
   
    public Integer getDeliveryId() {
        return this.deliveryId;
    }
    
    public void setDeliveryId(Integer deliveryId) {
        this.deliveryId = deliveryId;
    }
    public String getZoneName() {
        return this.zoneName;
    }
    
    public void setZoneName(String zoneName) {
        this.zoneName = zoneName;
    }
    public double getDeliveryCost() {
        return this.deliveryCost;
    }
    
    public void setDeliveryCost(double deliveryCost) {
        this.deliveryCost = deliveryCost;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


