package entity;
// Generated 08/07/2017 8:14:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail  implements java.io.Serializable {


     private Integer orderDetailId;
     private Order order;
     private Product product;
     private int prodQty;
     private Set orders = new HashSet(0);

    public OrderDetail() {
    }

	
    public OrderDetail(Order order, Product product, int prodQty) {
        this.order = order;
        this.product = product;
        this.prodQty = prodQty;
    }
    public OrderDetail(Order order, Product product, int prodQty, Set orders) {
       this.order = order;
       this.product = product;
       this.prodQty = prodQty;
       this.orders = orders;
    }
   
    public Integer getOrderDetailId() {
        return this.orderDetailId;
    }
    
    public void setOrderDetailId(Integer orderDetailId) {
        this.orderDetailId = orderDetailId;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getProdQty() {
        return this.prodQty;
    }
    
    public void setProdQty(int prodQty) {
        this.prodQty = prodQty;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


