package entity;
// Generated 08/07/2017 8:14:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer prodId;
     private SubCategory subCategory;
     private String prodName;
     private int prodQty;
     private double prodPrice;
     private String prodUrl;
     private String prodDesc;
     private Set orderDetails = new HashSet(0);

    public Product() {
    }

	
    public Product(SubCategory subCategory, String prodName, int prodQty, double prodPrice, String prodUrl, String prodDesc) {
        this.subCategory = subCategory;
        this.prodName = prodName;
        this.prodQty = prodQty;
        this.prodPrice = prodPrice;
        this.prodUrl = prodUrl;
        this.prodDesc = prodDesc;
    }
    public Product(SubCategory subCategory, String prodName, int prodQty, double prodPrice, String prodUrl, String prodDesc, Set orderDetails) {
       this.subCategory = subCategory;
       this.prodName = prodName;
       this.prodQty = prodQty;
       this.prodPrice = prodPrice;
       this.prodUrl = prodUrl;
       this.prodDesc = prodDesc;
       this.orderDetails = orderDetails;
    }
   
    public Integer getProdId() {
        return this.prodId;
    }
    
    public void setProdId(Integer prodId) {
        this.prodId = prodId;
    }
    public SubCategory getSubCategory() {
        return this.subCategory;
    }
    
    public void setSubCategory(SubCategory subCategory) {
        this.subCategory = subCategory;
    }
    public String getProdName() {
        return this.prodName;
    }
    
    public void setProdName(String prodName) {
        this.prodName = prodName;
    }
    public int getProdQty() {
        return this.prodQty;
    }
    
    public void setProdQty(int prodQty) {
        this.prodQty = prodQty;
    }
    public double getProdPrice() {
        return this.prodPrice;
    }
    
    public void setProdPrice(double prodPrice) {
        this.prodPrice = prodPrice;
    }
    public String getProdUrl() {
        return this.prodUrl;
    }
    
    public void setProdUrl(String prodUrl) {
        this.prodUrl = prodUrl;
    }
    public String getProdDesc() {
        return this.prodDesc;
    }
    
    public void setProdDesc(String prodDesc) {
        this.prodDesc = prodDesc;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }




}


